Committing updated ./configure script, created from 'autoconf -I autoconf_in' in kom-rsvp root directory, used autoconf 2.59.  Includes the VLSR's custom ./configure options:
  --with-force10-software-v6
  --with-switch-vendor-model
  --with-switch-ctrl-port
  --enable-switch-port-shutdown
  --enable-switch-cli-access
  --with-switch-cli-type

Minor updates to RSVP_config.h.in, to make descriptions a little more
descriptive..



git-svn-id: file:///var/www/svn/dragon-sw/trunk@882 625cd551-afe4-0310-9ad4-9d199310cf85

diff --git a/dragon-sw/kom-rsvp/configure b/dragon-sw/kom-rsvp/configure
--- a/dragon-sw/kom-rsvp/configure
+++ b/dragon-sw/kom-rsvp/configure
@@ -860,6 +860,7 @@ Optional Features:
  --enable-virt		compile virtual networking (disabled by default)
  --disable-real		do not compile real networking (enabled by default)
  --enable-performance	build for performance tests (disabled by default)
+ --enable-switch-port-shutdown	enable VLSR switch port shutdown (disabled by default)
  --disable-checking	disable runtime checks (enabled by default)
  --disable-logging	disable log output (enabled by default)
  --disable-api		do not build API support (enabled by default)
@@ -878,11 +879,16 @@ Optional Features:
  --disable-memopt	do not use memory optimization (enabled by default)
  --disable-altq		do not use ALTQ on FreeBSD (enabled by default)
  --disable-cbq		do not use CBQ (enabled by default)
+ --enable-switch-cli-access	enable VLSR switch CLI access (disabled by default)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --with-altq-includes=DIR	ALTQ include files are in non-standard DIR/altq
+ --with-force10-software-v6     add VLSR support for Force10 FTOS 6-2-1-x (disabled by default)
+ --with-switch-vendor-model=X   set VLSR switch vendor model (prompt by default)
+ --with-switch-ctrl-port=#      set VLSR control port (prompt by default)
+ --with-switch-cli-type=X   set VLSR switch CLI type (prompt by default)
  --with-mpls=PATH		path to MPLS library (disabled by default)
  --with-mpls-includes=DIR	mpls include files are in non-standard DIR/mpls
  --with-ns2dir=DIR		ns2-allinone in DIR (disabled by default)
@@ -3205,7 +3211,6 @@ _ACEOF
 fi
 
 fi
-
 # AC_PROG_MAKE_SET
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
@@ -3541,6 +3546,7 @@ _ACEOF
 if test $NUMCPUS && test $NUMCPUS -gt 1; then
 	MAKEFLAGS="-j $NUMCPUS"
 fi
+
 
 
 echo "$as_me:$LINENO: checking whether byte ordering is bigendian" >&5
@@ -5548,6 +5554,27 @@ echo "${ECHO_T}disabled" >&6
 fi
 
 
+# Check whether --enable-switch-port-shutdown or --disable-switch-port-shutdown was given.
+if test "${enable_switch_port_shutdown+set}" = set; then
+  enableval="$enable_switch_port_shutdown"
+
+else
+  enable_switch_port_shutdown=no
+fi;
+echo "$as_me:$LINENO: checking for VLSR switch port shutdown" >&5
+echo $ECHO_N "checking for VLSR switch port shutdown... $ECHO_C" >&6
+if test "$enable_switch_port_shutdown" = "yes"; then
+	echo "$as_me:$LINENO: result: enabled" >&5
+echo "${ECHO_T}enabled" >&6
+	cat >>confdefs.h <<\_ACEOF
+#define ENABLE_SWITCH_PORT_SHUTDOWN 1
+_ACEOF
+
+else
+	echo "$as_me:$LINENO: result: disabled" >&5
+echo "${ECHO_T}disabled" >&6
+fi
+
 SAVE_LIBS=$LIBS
 LIBS=
 
@@ -6802,12 +6829,193 @@ echo "${ECHO_T}disabled" >&6
 fi
 
 
+# Check whether --with-force10-software-v6 or --without-force10-software-v6 was given.
+if test "${with_force10_software_v6+set}" = set; then
+  withval="$with_force10_software_v6"
+  with_force10_software_v6=$withval
+else
+  with_force10_software_v6="no"
+fi;
+if test "$with_force10_software_v6" = "yes"; then
+	cat >>confdefs.h <<\_ACEOF
+#define FORCE10_SOFTWARE_V6 1
+_ACEOF
+
+fi
+
+
+# Check whether --with-switch-vendor-model or --without-switch-vendor-model was given.
+if test "${with_switch_vendor_model+set}" = set; then
+  withval="$with_switch_vendor_model"
+  with_switch_vendor_model=$withval
+else
+  with_switch_vendor_model="no"
+fi;
+if test "$with_switch_vendor_model" = "no"; then
+	echo $ECHO_N "
+
+*** Setting the vendor/model number of VLSR switch:
+
+It is recommended that you provide the vendor & model number of the
+switch being controlled by the VLSR.  If you do not know the switch
+vendor/model, use the default value of 'AutoDetect'.  The VLSR will
+then attempt to detect the switch vendor and model via SNMP.
+RFC2674-compliant switches should work with 'AutoDetect'.
+
+Valid options are: AutoDetect, Force10E600, RaptorER1010.
+
+Switch Vendor/Model number (Default: AutoDetect): $ECHO_C"
+
+       read tmpinput
+       if test "$tmpinput" = ""; then
+	  tmpinput="AutoDetect"
+       fi
+       eval with_switch_vendor_model=\$tmpinput
+fi;
+echo setting VLSR switch vendor model to $with_switch_vendor_model
+cat >>confdefs.h <<_ACEOF
+#define SWITCH_VENDOR_MODEL $with_switch_vendor_model
+_ACEOF
+
+
+
+# Check whether --with-switch-ctrl-port or --without-switch-ctrl-port was given.
+if test "${with_switch_ctrl_port+set}" = set; then
+  withval="$with_switch_ctrl_port"
+  with_switch_ctrl_port=$withval
+else
+  with_switch_ctrl_port="no"
+fi;
+if test "$with_switch_ctrl_port" = "no"; then
+	echo $ECHO_N "
+
+*** Setting the VLSR switch control port:
+
+A switch port is used by network administrators to login and execute
+management commands on the switch. Generally the switch control port
+should be excluded from data plane operations. In other words, we
+should never move the switch control port to some other VLAN and
+risking losing the management connectivity to the switch.  Many
+switches have out-of-band (OOB) management ports so that this
+condition cannot occur.
+
+Providing the --with-switch-ctrl-port=\"x\" parameter to ./configure
+will avoid this prompt.
+
+Switch control port to use (Default: 255): $ECHO_C"
+
+       read tmpinput
+       if test "$tmpinput" = ""; then
+	  tmpinput="255"
+       fi
+       eval with_switch_ctrl_port=\$tmpinput
+fi;
+echo setting VLSR switch control port to $with_switch_ctrl_port
+cat >>confdefs.h <<_ACEOF
+#define SWITCH_CTRL_PORT $with_switch_ctrl_port
+_ACEOF
+
+
+# Check whether --enable-switch-cli-access or --disable-switch-cli-access was given.
+if test "${enable_switch_cli_access+set}" = set; then
+  enableval="$enable_switch_cli_access"
+
+else
+  enable_switch_cli_access=no
+fi;
+echo "$as_me:$LINENO: checking for VLSR switch CLI access" >&5
+echo $ECHO_N "checking for VLSR switch CLI access... $ECHO_C" >&6
+if test "$enable_switch_cli_access" = "yes"; then
+	echo "$as_me:$LINENO: result: enabled" >&5
+echo "${ECHO_T}enabled" >&6
+	echo $ECHO_N "
+
+*** Setting username and password to access switch via CLI:
+
+With the --enable-switch-cli-access option,
+you need to provide the username and password.
+
+Username (Default: unknown): $ECHO_C"
+
+	read tmpinput
+	if test "$tmpinput" = ""; then
+	    tmpinput="unknown"
+	fi
+	eval switch_cli_username=\$tmpinput
+
+	stty -echo
+	echo $ECHO_N "Password (Default: unknown): $ECHO_C"
+	read tmpinput
+	if test "$tmpinput" = ""; then
+	    tmpinput="unknown"
+	fi
+	eval switch_cli_password=\$tmpinput
+	stty echo
+	echo \*\*\*\*\*\*\*\*
+	cat >>confdefs.h <<_ACEOF
+#define CLI_USERNAME $switch_cli_username
+_ACEOF
+
+	cat >>confdefs.h <<_ACEOF
+#define CLI_PASSWORD $switch_cli_password
+_ACEOF
+
+else
+	echo "$as_me:$LINENO: result: disabled" >&5
+echo "${ECHO_T}disabled" >&6
+fi
+
+if test "$enable_switch_cli_access" = "yes"; then
+        echo $ECHO_N "
+
+*** Setting CLI Session Type:
+
+With the --enable-switch-cli-access option,
+you also need to specify the CLI session type as either TELNET or SSH.
+This can also be specified by --with-switch-cli-type=(telnet|ssh)
+
+CLI Session Type (Default: none): $ECHO_C"
+
+       read tmpinput
+       eval with_switch_cli_type=\$tmpinput
+fi
+
+if test "$with_switch_cli_type" = "ssh"; then
+    if test ! -f "/usr/local/bin/expect" && test ! -f "/usr/bin/expect"; then
+       { { echo "$as_me:$LINENO: error: Using SSH to control VLSR switch requires the 'expect' package (http://expect.nist.gov) to be installed!" >&5
+echo "$as_me: error: Using SSH to control VLSR switch requires the 'expect' package (http://expect.nist.gov) to be installed!" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+fi
+if test "$with_switch_cli_type" = "telnet"; then
+    eval switch_cli_type="CLI_TELNET"
+elif test "$with_switch_cli_type" = "ssh"; then
+    eval switch_cli_type="CLI_SSH"
+else
+    eval switch_cli_type="CLI_NONE"
+fi
+echo setting VLSR switch CLI type to $switch_cli_type
+cat >>confdefs.h <<_ACEOF
+#define CLI_SESSION_TYPE $switch_cli_type
+_ACEOF
+
+
+
+# Check whether --with-switch-cli-type or --without-switch-cli-type was given.
+if test "${with_switch_cli_type+set}" = set; then
+  withval="$with_switch_cli_type"
+  with_switch_cli_type=$withval
+else
+  with_switch_cli_type="no"
+fi;
+
+
 # Check whether --with-mpls or --without-mpls was given.
 if test "${with_mpls+set}" = set; then
   withval="$with_mpls"
-
-else
   with_mpls=$withval
+else
+  with_mpls="no"
 fi;
 if test "$enable_performance" = "yes"; then
 	if test "$with_mpls" != "no"; then
@@ -7320,20 +7528,6 @@ echo "${ECHO_T}disabled" >&6
 fi
 
 
-# Check whether --with-switch-ctrl-port was given.
-if test "${with_switch_ctrl_port+set}" = set; then
-  withval="$with_switch_ctrl_port"
-  with_switch_ctrl_port=$withval
-else
-  with_switch_ctrl_port=no
-fi;
-
-# Check whether --with-force10-software-v6 was given.
-if test "${with_force10_software_v6+set}" = set; then
-cat >>confdefs.h <<_ACEOF
-#define FORCE10_SOFTWARE_V6
-_ACEOF
-fi;
 
 echo "$as_me:$LINENO: checking for crypto" >&5
 echo $ECHO_N "checking for crypto... $ECHO_C" >&6
@@ -8654,144 +8848,6 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
 
 _ACEOF
 
-if test "$with_switch_vendor_model" = ""; then
-echo $ECHO_N "
-
-*** Setting the vendor/model type of VLSR switch:
-
-      You are highly recommended to provide the vendor/model ID 
-(case sensitive). If you do not know the switch vendor/model, it's 
-set to a default value: 'AutoDetect.' VLSR will try detecting the switch
-vendor and model via SNMP. 
-
-Switch Vendor/Model ID [AutoDetect]: $ECHO_C"
-read tmpinput
-if test "$tmpinput" = ""; then
-    tmpinput="AutoDetect"
-fi
-else
-    tmpinput="$with_switch_vendor_type"
-fi;
-
-eval switch_vendor_model=\$tmpinput
-
-cat >>confdefs.h <<_ACEOF
-#define SWITCH_VENDOR_MODEL $switch_vendor_model
-_ACEOF
-
-
-if test "$with_switch_ctrl_port" = "no"; then
-echo $ECHO_N "
-
-*** Switch Control Port:
-
-   A switch control port is used by network administrators to login
-and execute management commands on the switch. Generally the switch
-control port should be excluded from data plane operations. In other
-words, we should avoid moving around the switch control port and
-risking losing the management connectivity to the switch.
-
-   Providing the --with-switch-ctrl-port=\"x\" parameter to
-./configure will avoid this prompt.
-
-Switch control port to use [1]: $ECHO_C"
-
-read tmpinput
-if test "$tmpinput" = ""; then
-    tmpinput="255"
-fi
-eval with_switch_ctrl_port=\$tmpinput
-
-fi;
-
-cat >>confdefs.h <<_ACEOF
-#define SWITCH_CTRL_PORT $with_switch_ctrl_port
-_ACEOF
-
-if test "$enable_switch_cli_access" = "yes"; then
-echo $ECHO_N "
-
-*** Setting username and password to access switch via CLI:
-
-   With the --enable-switch-cli-access option, 
-you need to provide the username and password.
-
-Username [unknown]: $ECHO_C"
-read tmpinput
-if test "$tmpinput" = ""; then
-    tmpinput="unknown"
-fi
-eval switch_cli_username=\$tmpinput
-
-stty -echo
-echo $ECHO_N "Password [unknown]: $ECHO_C"
-read tmpinput
-if test "$tmpinput" = ""; then
-    tmpinput="unknown"
-fi
-eval switch_cli_password=\$tmpinput
-stty echo
-
-if test "$with_switch_cli_type" = ""; then
-echo $ECHO_N "
-
-*** Setting CLI Session Type:
-
-   With the --enable-switch-cli-access option, 
-you need to specify the CLI session type as either TELNET or SSH.
-This can also be specified by --enable-switch-cli-type [telnet|ssh]
-
-CLI Session Type [none]: $ECHO_C"
-read tmpinput
-if test "$tmpinput" = "telnet"; then
-    tmpinput="CLI_TELNET"
-elif test "$tmpinput" = "ssh"; then
-    tmpinput="CLI_SSH"
-else
-    tmpinput="CLI_NONE"
-fi
-elif test "$with_switch_cli_type" = "telnet"; then
-    tmpinput="CLI_TELNET"
-elif test "$with_switch_cli_type" = "ssh"; then
-    tmpinput="CLI_SSH"
-else
-    eval switch_cli_type="CLI_NONE"
-fi; #if test "$with_switch_cli_type"
-
-eval switch_cli_type=\$tmpinput
-
-fi;
-
-if test "$switch_cli_type" = ""; then
-if test "$with_switch_cli_type" = "telnet"; then
-    eval switch_cli_type="CLI_TELNET"
-elif test "$with_switch_cli_type" = "ssh"; then
-    eval switch_cli_type="CLI_SSH"
-    
-    echo "$as_me:$LINENO: checking 'expect' command" >&5
-    echo $ECHO_N "checking 'expect' command... $ECHO_C" >&6
-    if ! -f "/usr/local/bin/expect" && ! -f "/usr/bin/expect"; then
-        { { echo "$as_me:$LINENO: error: \"Using SSH to control VLSR switch requires the 'expect' package (http://expect.nist.gov) to be installed!\"" >&5
-        echo "$as_me: error: \"Using SSH to control VLSR switch requires the 'expect' package (http://expect.nist.gov) to be installed!\"" >&2;}
-       { (exit 1); exit 1; }; }
-    fi;
-
-fi
-    eval switch_cli_type="CLI_NONE"
-fi;
-
-cat >>confdefs.h <<_ACEOF
-#define CLI_USERNAME "$switch_cli_username"
-#define CLI_PASSWORD "$switch_cli_password"
-#define CLI_SESSION_TYPE $switch_cli_type
-_ACEOF
-
-if test "$enable_switch_port_shutdown" = "yes"; then
-cat >>confdefs.h <<_ACEOF
-#define ENABLE_SWITCH_PORT_SHUTDOWN
-_ACEOF
-fi;
-
 # Transform confdefs.h into two sed scripts, `conftest.defines' and
 # `conftest.undefs', that substitutes the proper values into
 # config.h.in to produce config.h.  The first handles `#define'
@@ -8998,4 +9054,3 @@ else
 	echo export RSVP_BUILD_DIR=$RSVP_BUILD_DIR
 fi
 echo
-
