Changes to kom-rsvp configure.in and MakeConfig.in necessary to check for libxml2 and add the appropriate -I... -L... -lxml2 directives when compiling.
Also re-ran 'autoconf -I autoconf_in' in the kom-rsvp directory after updating configure.in.

NOTE:  We could avoid the check for net-snmp in do_build.sh (e.g. 
'determine a valid path for net-snmp header files') by modifying
kom-rsvp/configure.in in a similar manner for the --with-snmp option...
(So that configure automatically finds whether netsnmp is installed
in /usr or /usr/local and does not rely on the do_build.sh script
to pass the right option to --with-snmp...)



git-svn-id: file:///var/www/svn/dragon-sw/trunk@2161 625cd551-afe4-0310-9ad4-9d199310cf85

diff --git a/dragon-sw/kom-rsvp/configure b/dragon-sw/kom-rsvp/configure
--- a/dragon-sw/kom-rsvp/configure
+++ b/dragon-sw/kom-rsvp/configure
@@ -700,6 +700,8 @@ MPLS_INCLUDE
 MPLS_LIB
 NS2_DIR
 SNMP_INCLUDE
+XML_INCLUDE
+XML_LIB
 DMALLOC_INCLUDE
 DMALLOC_LIB
 NEWMAT_INCLUDE
@@ -1332,7 +1334,8 @@ Optional Packages:
  --with-mpls=PATH		path to MPLS library (disabled by default)
  --with-mpls-includes=DIR	mpls include files are in non-standard DIR/mpls
  --with-ns2dir=DIR		ns2-allinone in DIR (disabled by default)
- --with-snmp=DIR		use SNMP in DIR (disabled by default)
+ --with-snmp=DIR		use SNMP in DIR (enabled by default)
+ --with-libxml=DIR		use libxml in DIR (enabled by default)
  --with-dmalloc=DIR		use dmalloc in DIR (disabled by default)
  --with-newmat=PREFIX	newmat is in non-standard path (default: /usr/local)
 
@@ -8080,6 +8083,204 @@ fi
 
 
 
+SAVE_LIBS=$LIBS
+LIBS=
+
+# Check whether --with-libxml was given.
+if test "${with_libxml+set}" = set; then
+  withval=$with_libxml; with_libxml=$withval
+else
+  with_libxml=yes
+fi
+
+if test "$with_libxml" = "yes"; then
+	{ echo "$as_me:$LINENO: checking for libxml2 include files" >&5
+echo $ECHO_N "checking for libxml2 include files... $ECHO_C" >&6; }
+	if test -e "/usr/include/libxml2/libxml/parser.h"; then
+	   LDFLAGS="-L/usr/lib -lxml2"
+	   XML_INCLUDE="-I/usr/include/libxml2"
+	   XML_LIB="$LDFLAGS $LIBS"
+	   { echo "$as_me:$LINENO: result: enabled, found in /usr" >&5
+echo "${ECHO_T}enabled, found in /usr" >&6; }
+	elif test -e "/usr/local/include/libxml2/libxml/parser.h"; then
+	   LDFLAGS="-L/usr/local/lib -lxml2"
+	   XML_INCLUDE="-I/usr/local/include/libxml2"
+	   XML_LIB="$LDFLAGS $LIBS"
+	   { echo "$as_me:$LINENO: result: enabled, found in /usr/local" >&5
+echo "${ECHO_T}enabled, found in /usr/local" >&6; }
+	else
+	   { { echo "$as_me:$LINENO: error: not found, please make sure you have the libxml2 include files installed" >&5
+echo "$as_me: error: not found, please make sure you have the libxml2 include files installed" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	{ echo "$as_me:$LINENO: checking for libxml2" >&5
+echo $ECHO_N "checking for libxml2... $ECHO_C" >&6; }
+	{ echo "$as_me:$LINENO: checking for xmlParseFile in -lxml2" >&5
+echo $ECHO_N "checking for xmlParseFile in -lxml2... $ECHO_C" >&6; }
+if test "${ac_cv_lib_xml2_xmlParseFile+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lxml2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char xmlParseFile ();
+int
+main ()
+{
+return xmlParseFile ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_xml2_xmlParseFile=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_xml2_xmlParseFile=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_xml2_xmlParseFile" >&5
+echo "${ECHO_T}$ac_cv_lib_xml2_xmlParseFile" >&6; }
+if test $ac_cv_lib_xml2_xmlParseFile = yes; then
+  HAVE_LIBXML=yes
+fi
+
+	if test "${HAVE_LIBXML}" = ""; then
+	   { { echo "$as_me:$LINENO: error: cannot find the libxml2 library, cannot continue with build!" >&5
+echo "$as_me: error: cannot find the libxml2 library, cannot continue with build!" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+elif test "$with_libxml" != "no"; then
+	{ echo "$as_me:$LINENO: checking for libxml2 include files" >&5
+echo $ECHO_N "checking for libxml2 include files... $ECHO_C" >&6; }
+	if test -e "/usr/include/libxml2/libxml/parser.h"; then
+	   LDFLAGS="-L$with_libxml/lib -lxml2"
+	   XML_INCLUDE="-I/usr/include/libxml2"
+	   XML_LIB="$LDFLAGS $LIBS"
+	   { echo "$as_me:$LINENO: result: enabled, found in $with_libxml" >&5
+echo "${ECHO_T}enabled, found in $with_libxml" >&6; }
+	else
+	   { { echo "$as_me:$LINENO: error: not found, please make sure you have the libxml2 include files installed" >&5
+echo "$as_me: error: not found, please make sure you have the libxml2 include files installed" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	{ echo "$as_me:$LINENO: checking for libxml2" >&5
+echo $ECHO_N "checking for libxml2... $ECHO_C" >&6; }
+	{ echo "$as_me:$LINENO: checking for xmlParseFile in -lxml2" >&5
+echo $ECHO_N "checking for xmlParseFile in -lxml2... $ECHO_C" >&6; }
+if test "${ac_cv_lib_xml2_xmlParseFile+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lxml2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char xmlParseFile ();
+int
+main ()
+{
+return xmlParseFile ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_xml2_xmlParseFile=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_xml2_xmlParseFile=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_xml2_xmlParseFile" >&5
+echo "${ECHO_T}$ac_cv_lib_xml2_xmlParseFile" >&6; }
+if test $ac_cv_lib_xml2_xmlParseFile = yes; then
+  HAVE_LIBXML=yes
+fi
+
+	if test "${HAVE_LIBXML}" = ""; then
+	   { { echo "$as_me:$LINENO: error: cannot find the libxml2 library, cannot continue with build!" >&5
+echo "$as_me: error: cannot find the libxml2 library, cannot continue with build!" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+else
+	{ { echo "$as_me:$LINENO: error: Sorry, the dragon-sw package cannot currently be built without libxml2" >&5
+echo "$as_me: error: Sorry, the dragon-sw package cannot currently be built without libxml2" >&2;}
+   { (exit 1); exit 1; }; }
+	XML_INCLUDE=""
+fi
+
+LDFLAGS=
+LIBS=$SAVE_LIBS
+
 { echo "$as_me:$LINENO: checking for crypto" >&5
 echo $ECHO_N "checking for crypto... $ECHO_C" >&6; }
 
@@ -8400,6 +8601,8 @@ echo "${ECHO_T}enabled in $with_newmat" >&6; }
 echo "${ECHO_T}disabled" >&6; }
 	fi
 fi
+
+
 
 
 
@@ -9122,6 +9325,8 @@ MPLS_INCLUDE!$MPLS_INCLUDE$ac_delim
 MPLS_LIB!$MPLS_LIB$ac_delim
 NS2_DIR!$NS2_DIR$ac_delim
 SNMP_INCLUDE!$SNMP_INCLUDE$ac_delim
+XML_INCLUDE!$XML_INCLUDE$ac_delim
+XML_LIB!$XML_LIB$ac_delim
 DMALLOC_INCLUDE!$DMALLOC_INCLUDE$ac_delim
 DMALLOC_LIB!$DMALLOC_LIB$ac_delim
 NEWMAT_INCLUDE!$NEWMAT_INCLUDE$ac_delim
@@ -9131,10 +9336,9 @@ PTHREAD_LIB!$PTHREAD_LIB$ac_delim
 RSVP_BUILD_DIR!$RSVP_BUILD_DIR$ac_delim
 PKG_BASEDIR!$PKG_BASEDIR$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
-LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 96; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -9166,6 +9370,50 @@ N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
 ' >>$CONFIG_STATUS <conf$$subs.sed
 rm -f conf$$subs.sed
 cat >>$CONFIG_STATUS <<_ACEOF
+CEOF$ac_eof
+_ACEOF
+
+
+ac_delim='%!_!# '
+for ac_last_try in false false false false false :; do
+  cat >conf$$subs.sed <<_ACEOF
+LTLIBOBJS!$LTLIBOBJS$ac_delim
+_ACEOF
+
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 1; then
+    break
+  elif $ac_last_try; then
+    { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
+echo "$as_me: error: could not make $CONFIG_STATUS" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    ac_delim="$ac_delim!$ac_delim _$ac_delim!! "
+  fi
+done
+
+ac_eof=`sed -n '/^CEOF[0-9]*$/s/CEOF/0/p' conf$$subs.sed`
+if test -n "$ac_eof"; then
+  ac_eof=`echo "$ac_eof" | sort -nru | sed 1q`
+  ac_eof=`expr $ac_eof + 1`
+fi
+
+cat >>$CONFIG_STATUS <<_ACEOF
+cat >"\$tmp/subs-2.sed" <<\CEOF$ac_eof
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
+_ACEOF
+sed '
+s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
+s/^/s,@/; s/!/@,|#_!!_#|/
+:n
+t n
+s/'"$ac_delim"'$/,g/; t
+s/$/\\/; p
+N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
+' >>$CONFIG_STATUS <conf$$subs.sed
+rm -f conf$$subs.sed
+cat >>$CONFIG_STATUS <<_ACEOF
+:end
+s/|#_!!_#|//g
 CEOF$ac_eof
 _ACEOF
 
@@ -9413,7 +9661,7 @@ s&@abs_builddir@&$ac_abs_builddir&;t t
 s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed 's/|#_!!_#|//g' >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
