Compilation fixes under gcc3.4. Have incoporated all changes in jason_force10 branch. Fixed new bugs. Now the jason_force10 branch is obsolete.
git-svn-id: file:///var/www/svn/dragon-sw/trunk@807 625cd551-afe4-0310-9ad4-9d199310cf85

diff --git a/dragon-sw/kom-rsvp/configure b/dragon-sw/kom-rsvp/configure
--- a/dragon-sw/kom-rsvp/configure
+++ b/dragon-sw/kom-rsvp/configure
@@ -7212,7 +7212,7 @@ fi;
 if test "$BUILD_NS2" = "yes"; then with-snmp=no; fi
 if test "$with_snmp" = "yes"; then
 	with_snmp=/usr
-	LDFLAGS="-lcrypto -lm -lnetsnmp"
+	LDFLAGS="-L$with_snmp/lib -lcrypto -lm -lnetsnmp"
 elif test "$with_snmp" != "no"; then
          LDFLAGS="-L$with_snmp/lib -lcrypto -lm -lnetsnmp"
 fi
@@ -7320,6 +7320,87 @@ echo "${ECHO_T}disabled" >&6
 fi
 
 
+
+echo "$as_me:$LINENO: checking for crypto" >&5
+echo $ECHO_N "checking for crypto... $ECHO_C" >&6
+
+echo "$as_me:$LINENO: checking for SSLeay in -lcrypto" >&5
+echo $ECHO_N "checking for SSLeay in -lcrypto... $ECHO_C" >&6
+if test "${ac_cv_lib_crypto_SSLeay+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcrypto  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SSLeay ();
+int
+main ()
+{
+SSLeay ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_crypto_SSLeay=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_crypto_SSLeay=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_crypto_SSLeay" >&5
+echo "${ECHO_T}$ac_cv_lib_crypto_SSLeay" >&6
+if test $ac_cv_lib_crypto_SSLeay = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBCRYPTO 1
+_ACEOF
+
+  LIBS="-lcrypto $LIBS"
+
+fi
+
+if test "$ac_cv_lib_crypto_SSLeay" = "no"; then
+    new_libs="`echo ${LIBS} | sed -e 's/-lcrypto//g'`"
+    LIBS="${new_libs}"
+fi
 
 SAVE_LIBS=$LIBS
 LIBS=
